# project Information
site_name: John Brereton
site_author: 'John Brereton'
site_url: 'http://jbrereton.com'
site_dir: '/var/www/html'

# Repository
repo_name: 
repo_url: https://github.com/johnBrereton
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2018 - 2022 John Brereton'

# Page Tree
nav:
  - Home: index.md
  - 3D Printing: 3d-Printing.md
  - FTC Team 12601: FTC.md
  - Projects:
    - CNC: Projects/CNC.md
    - Home-Automation: Projects/Home-Automation.md
    - Home-Network: Projects/Home-Network.md
    - Raspberry Pi VPN: Projects/Pi-VPN.md
    - Response to COVID-19: Projects/COVID-19.md
    - This Website: Projects/Website.md

# Configuration
theme:
  name: material
  #custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
  palette:
    scheme: slate
    primary: blue
    accent: orange
  icon:
    logo: 'material/console'
  favicon: 'img/favicon.png'

# Extras
extra:
  disqus: 'johns-website'
  social:
    - icon: 'material/email'
      link: 'mailto:john@jbrereton.com'
    - icon: 'material/phone'
      link: 'tel:9085008621'
    - icon: 'material/github'
      link: 'https://github.com/johnBrereton'
    - icon: 'material/linkedin'
      link: 'https://www.linkedin.com/in/johnbrereton06/'
    - icon: 'material/instagram'
      link: 'https://www.instagram.com/johnbrereton_/'

# Google Analytics
google_analytics:
  - 'UA-129700516-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized